[en]
title = "My blog"
weight = 2
label = "English"
contentDir = "content/english"
[en.params]
direction = "ltr"

[zh]
title = "我的博客"                  # 中文站点标题
weight = 1                         # 
label = "中文（简体）"              # 语言切换按钮里显示这两个字（也可写 ZH）
contentDir = "content/Chinese"          # ← 中文内容放这个文件夹
[zh.params]
direction = "ltr"          # 中文从左到右



